name: Trigger Portfolio Tests

on:
  push:
    branches: [ main ]  
  workflow_dispatch:
  workflow_run:  # This triggers after deploy workflow completes
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    # Only run if the previous workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    steps:
      - name: Check if TEST_REPO_TOKEN exists
        run: |
          if [ -z "${{ secrets.TEST_REPO_TOKEN }}" ]; then
            echo "TEST_REPO_TOKEN secret is not configured"
            echo "Please add it in Settings → Secrets and variables → Actions"
            exit 1
          else
            echo "TEST_REPO_TOKEN secret is configured"
          fi
      
      - name: Wait for GitHub Pages deployment (if triggered by workflow_run)
        if: github.event_name == 'workflow_run'
        run: |
          echo "⏳ Waiting for GitHub Pages to update..."
          sleep 30  # Give GitHub Pages time to deploy
      
      - name: Trigger tests in test repository
        run: |
          echo "Triggering tests for portfolio update..."
          
          # Prepare payload based on event type
          if [ "${{ github.event_name }}" == "workflow_run" ]; then
            COMMIT_SHA="${{ github.event.workflow_run.head_sha }}"
            COMMIT_MESSAGE="${{ github.event.workflow_run.head_commit.message }}"
            BRANCH="${{ github.event.workflow_run.head_branch }}"
            PUSHER="${{ github.event.workflow_run.head_commit.author.name }}"
          else
            COMMIT_SHA="${{ github.sha }}"
            COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
            BRANCH="${{ github.ref_name }}"
            PUSHER="${{ github.event.head_commit.author.name }}"
          fi
          
          echo "Payload details:"
          echo "  - Commit SHA: $COMMIT_SHA"
          echo "  - Branch: $BRANCH"
          echo "  - Pusher: $PUSHER"
          echo "  - Event type: ${{ github.event_name }}"
          
          response=$(curl -s -w "HTTP_STATUS:%{http_code}" -X POST \
          -H "Authorization: token ${{ secrets.TEST_REPO_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/Arijit06/CI-CD-Integration-with-Selenium-Java-/dispatches \
          -d "{
            \"event_type\": \"portfolio-updated\",
            \"client_payload\": {
              \"portfolio_url\": \"https://arijit06.github.io/ArijitSinghaRoy/\",
              \"commit_sha\": \"$COMMIT_SHA\",
              \"commit_message\": \"$COMMIT_MESSAGE\",
              \"branch\": \"$BRANCH\",
              \"pusher\": \"$PUSHER\",
              \"triggered_at\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",
              \"source_repo\": \"${{ github.repository }}\"
            }
          }")
          
          # Extract HTTP status
          http_status=$(echo $response | grep -o "HTTP_STATUS:[0-9]*" | cut -d: -f2)
          body=$(echo $response | sed -E 's/HTTP_STATUS:[0-9]*$//')
          
          echo "HTTP Response Status: $http_status"
          
          if [ "$http_status" -eq 204 ]; then
            echo "Test trigger sent successfully!"
            echo "The test repository should now start running portfolio tests."
          else
            echo "Failed to trigger tests. HTTP Status: $http_status"
            echo "Response: $body"
            exit 1
          fi
      
      - name: Wait for test workflow to start
        run: |
          echo "Waiting for test workflow to start..."
          sleep 10
          
          # Check if the test workflow was triggered
          response=$(curl -s -H "Authorization: token ${{ secrets.TEST_REPO_TOKEN }}" \
            "https://api.github.com/repos/Arijit06/CI-CD-Integration-with-Selenium-Java-/actions/runs?per_page=5")
          
          echo "Recent workflow runs in test repository:"
          echo "$response" | jq -r '.workflow_runs[] | select(.created_at > (now - 300 | strftime("%Y-%m-%dT%H:%M:%SZ"))) | "Run #\(.run_number): \(.name) - \(.status) (\(.created_at))"' 2>/dev/null || echo "Could not parse recent runs"
      
      - name: Provide verification links
        run: |
          echo "Portfolio test trigger completed!"
          echo ""
          echo "Verify the integration worked:"
          echo ""
          echo "1. **Check Test Repository Actions:**"
          echo "   https://github.com/Arijit06/CI-CD-Integration-with-Selenium-Java-/actions"
          echo ""
          echo "2. **Look for 'Portfolio Tests - Cross Repository Trigger' workflow run**"
          echo "   - Should show as 'Running' or 'Completed'"
          echo "   - Check the timestamp matches this trigger"
          echo ""
          echo "3. **Verify payload was received:**"
          echo "   - Open the test workflow run"
          echo "   - Check 'Display trigger information' step"
          echo "   - Should show your commit details"
          echo ""
          echo "Triggered with:"
          echo "  - Portfolio URL: https://arijit06.github.io/ArijitSinghaRoy/"
          echo "  - Event: ${{ github.event_name }}"
          echo "  - Repository: ${{ github.repository }}"
