name: Trigger Portfolio Tests

on:
  push:
    branches: [ main ]  
  workflow_dispatch:
  workflow_run:  # This triggers after deploy workflow completes
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    # Only run if the previous workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    steps:
      - name: Check if TEST_REPO_TOKEN exists
        run: |
          if [ -z "${{ secrets.TEST_REPO_TOKEN }}" ]; then
            echo "TEST_REPO_TOKEN secret is not configured"
            exit 1
          else
            echo "TEST_REPO_TOKEN secret is configured"
          fi
      
      - name: Wait for GitHub Pages deployment (if triggered by workflow_run)
        if: github.event_name == 'workflow_run'
        run: |
          echo "⏳ Waiting for GitHub Pages to update..."
          sleep 30  # Give GitHub Pages time to deploy
      
      - name: Trigger tests in test repository
        run: |
          echo "🚀 Triggering tests for portfolio update..."
          
          # Prepare payload based on event type
          if [ "${{ github.event_name }}" == "workflow_run" ]; then
            COMMIT_SHA="${{ github.event.workflow_run.head_sha }}"
            COMMIT_MESSAGE="${{ github.event.workflow_run.head_commit.message }}"
            BRANCH="${{ github.event.workflow_run.head_branch }}"
            PUSHER="${{ github.event.workflow_run.head_commit.author.name }}"
          else
            COMMIT_SHA="${{ github.sha }}"
            COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
            BRANCH="${{ github.ref_name }}"
            PUSHER="${{ github.event.head_commit.author.name }}"
          fi
          
          echo "Payload details:"
          echo "  - Commit SHA: $COMMIT_SHA"
          echo "  - Branch: $BRANCH"
          echo "  - Pusher: $PUSHER"
          echo "  - Event type: ${{ github.event_name }}"
          
          response=$(curl -s -w "HTTP_STATUS:%{http_code}" -X POST \
          -H "Authorization: token ${{ secrets.TEST_REPO_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/Arijit06/CI-CD-Integration-with-Selenium-Java-/dispatches \
          -d "{
            \"event_type\": \"portfolio-updated\",
            \"client_payload\": {
              \"portfolio_url\": \"https://arijit06.github.io/ArijitSinghaRoy/\",
              \"commit_sha\": \"$COMMIT_SHA\",
              \"commit_message\": \"$COMMIT_MESSAGE\",
              \"branch\": \"$BRANCH\",
              \"pusher\": \"$PUSHER\",
              \"triggered_at\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",
              \"source_repo\": \"${{ github.repository }}\"
            }
          }")
          
          # Extract HTTP status
          http_status=$(echo $response | grep -o "HTTP_STATUS:[0-9]*" | cut -d: -f2)
          body=$(echo $response | sed -E 's/HTTP_STATUS:[0-9]*$//')
          
          echo "HTTP Response Status: $http_status"
          
          if [ "$http_status" -eq 204 ]; then
            echo "✅ Test trigger sent successfully!"
            echo "The test repository should now start running portfolio tests."
          elif [ "$http_status" -eq 404 ]; then
            echo "Repository dispatch failed with 404"
            echo "Possible causes:"
            echo "1. Target repository doesn't have a workflow listening to 'repository_dispatch'"
            echo "2. Workflow file might not be in the main branch"
            echo "3. Token might not have access to the repository"
            echo "Response: $body"
            exit 1
          elif [ "$http_status" -eq 401 ]; then
            echo "Authorization failed (401)"
            echo "Check if TEST_REPO_TOKEN has the right permissions:"
            echo "- repo (full control of repositories)"
            echo "- workflow (if needed for workflow_dispatch)"
            echo "Response: $body"
            exit 1
          else
            echo "Unexpected response: HTTP $http_status"
            echo "Response: $body"
            exit 1
          fi
      
      - name: Confirm trigger sent
        run: |
          echo "Portfolio test trigger completed!"
          echo ""
          echo "Check test progress at:"
          echo "https://github.com/Arijit06/CI-CD-Integration-with-Selenium-Java-/actions"
          echo ""
          echo "Triggered with:"
          echo "  - Portfolio URL: https://arijit06.github.io/ArijitSinghaRoy/"
          echo "  - Event: ${{ github.event_name }}"
          echo "  - Repository: ${{ github.repository }}"
